import Builder from "@/bot/globals/classes/command/global"

import { MessageFlags } from "discord.js"

export default new Builder()
	.build((builder) => builder
		.setName("code")
		.setDescription("Code related commands.")
		.addSubcommandGroup((subcommandgroup) => subcommandgroup
			.setName("generate")
			.setDescription("Generate a redeemable code.")
			.addSubcommand((subcommand) => subcommand
				.setName("satoshi")
				.setDescription("Generate a redeemable code for Satoshi.")
				.addNumberOption((option) => option
					.setName("amount")
					.setDescription("The amount of Satoshi to generate the code for.")
					.setRequired(true)
					.setMinValue(1)
					.setMaxValue(10000)
				)
				.addStringOption((option) => option
					.setName("duration")
					.setDescription("The duration for which the code will be valid (minimum: 10 minutes, maximum: 30 days).")
					.setRequired(false)
				)
				.addNumberOption((option) => option
					.setName("uses")
					.setDescription("The number of times the code can be used (minimum: 1, maximum: 100).")
					.setRequired(false)
					.setMinValue(1)
					.setMaxValue(100)
				)
			)
			.addSubcommand((subcommand) => subcommand
				.setName("usdt")
				.setDescription("Generate a redeemable code for USDT.")
				.addNumberOption((option) => option
					.setName("amount")
					.setDescription("The amount of USDT to generate the code for.")
					.setRequired(true)
					.setMinValue(1)
					.setMaxValue(10000)
				)
				.addStringOption((option) => option
					.setName("duration")
					.setDescription("The duration for which the code will be valid (minimum: 10 minutes, maximum: 30 days).")
					.setRequired(false)
				)
				.addNumberOption((option) => option
					.setName("uses")
					.setDescription("The number of times the code can be used (minimum: 1, maximum: 100).")
					.setRequired(false)
					.setMinValue(1)
					.setMaxValue(100)
				)
			)
			.addSubcommand((subcommand) => subcommand
				.setName("usdc")
				.setDescription("Generate a redeemable code for USDC.")
				.addNumberOption((option) => option
					.setName("amount")
					.setDescription("The amount of USDC to generate the code for.")
					.setRequired(true)
					.setMinValue(1)
					.setMaxValue(10000)
				)
				.addStringOption((option) => option
					.setName("duration")
					.setDescription("The duration for which the code will be valid (minimum: 10 minutes, maximum: 30 days).")
					.setRequired(false)
				)
				.addNumberOption((option) => option
					.setName("uses")
					.setDescription("The number of times the code can be used (minimum: 1, maximum: 100).")
					.setRequired(false)
					.setMinValue(1)
					.setMaxValue(100)
				)
			)
		)
		.addSubcommand((subcommand) => subcommand
			.setName("redeem")
			.setDescription("Redeem a redeemable code.")
			.addStringOption((option) => option
				.setName("code")
				.setDescription("The code to redeem.")
				.setRequired(true)
			)
		)
		.addSubcommand((subcommand) => subcommand
			.setName("list")
			.setDescription("List all codes generated by you, be it still claimable or already claimed.")
		)
	)
	.listen(async (ctx) => {
		const locale = ctx.interaction.locale,
			user = ctx.interaction.user
		await ctx.interaction.deferReply({ flags: MessageFlags.Ephemeral })
		switch (ctx.interaction.options.getSubcommandGroup(false)) {
			case "generate": {
				switch (ctx.interaction.options.getSubcommand(true)) {
					case "satoshi": {
						return ctx.interaction.editReply({
							content: "This command is not implemented yet. (#1)",
						})
					}
					case "usdt": {
						return ctx.interaction.editReply({
							content: "This command is not implemented yet. (#2)",
						})
					}
					case "usdc": {
						return ctx.interaction.editReply({
							content: "This command is not implemented yet. (#3)",
						})
					}
				}
			}
			default:
				switch (ctx.interaction.options.getSubcommand(true)) {
					case "redeem": {
						const code = ctx.interaction.options.getString("code", true)
						return ctx.interaction.editReply({
							content: `This command is not implemented yet. (#4) Code: ${code}`,
						})
					}
					case "list": {
						return ctx.interaction.editReply({
							content: "This command is not implemented yet. (#5)",
						})
					}
				}
		}
	})